# Generated by Django 4.1.2 on 2023-02-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainfooty4u", "0002_game"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ("-date_added",)},
        ),
    ]
